services:
  db:
    image: postgres:16
    restart: always
    container_name: rs_school_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 24082017
      POSTGRES_DB: rs-school-nest
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rs-network
      
  app:
    build: .
    container_name: rs_school_app
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:24082017@db:5432/rs-school-nest?schema=public"
      REST_PORT: 4000
    networks:
      - rs-network

volumes:
  pgdata:

networks:
  rs-network:
    driver: bridge
